# Generated by Django 3.2.5 on 2023-08-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modele', '0003_alter_modele_marque'),
        ('users', '0002_alter_personne_role'),
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='modele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modele.modele'),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='proprietaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.proprietaire'),
        ),
    ]
