name: Intégration Continue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2
      
    - name: Configuration de l'environnement Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Installation des dépendances
      run: pip install -r requirements.txt
      
